version: '3.7'

services:

  lucy:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME

      SLC_WEBHOOK: $SLC_WEBHOOK
    networks:
      - backend

networks:
  backend:
